# Generated by Django 3.0.8 on 2020-08-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_auto_20200808_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
