# Generated by Django 3.0.8 on 2020-08-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_auto_20200812_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
